package com.javabrains.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * @author Anjaiah upload entity Object
 *
 */
@Entity
@Table(name = "uploadfile")
public class Uploadfile {

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	// The contentType
	private String contentType;

	// The filesize name

	private long filesize;

	// The filepath name

	private String filepath;

	// ------------------------
	// PUBLIC METHODS
	// ------------------------

	public Uploadfile() {
	}

	public Uploadfile(long id) {
		this.id = id;
	}

	public Uploadfile(String contentType, String filepath, long filesize) {
		this.contentType = contentType;
		this.filesize = filesize;
		this.filepath = filepath;
	}

	// Getter and setter methods

	public long getId() {
		return id;
	}

	public String getContentType() {
		return contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public void setId(long value) {
		this.id = value;
	}

	public long getFilesize() {
		return filesize;
	}

	public void setFilesize(long value) {
		this.filesize = value;
	}

	public String getFilepath() {
		return filepath;
	}

	public void setFilepath(String value) {
		this.filepath = value;
	}

}
